--- 

- name: installing nginx in client1
  hosts: all
  tasks:
    - name: nginx install
      apt:
       name: nginx
       state: present
       update_cache: yes
    - name: nginx start
      service:
       name: nginx
       state: started
